### ISSUE TITLE
The sum of different gardening styles

### ISSUE THREAD

**Issue by erikpukinskis** [goodeggs/bites#34]
Specialization vs. generalism and how it affects robustness

**Comment by hazeledmands** [comment]
Hi @erikpukinskis!! 👋

**Comment by erikpukinskis** [comment]
👋 

Three specialists in different ways of gardening:

One just plants single plants and sings sweetly to them

One is only interested in a productive crop, doesn’t see the use in growing less than a row of anything

The other is entranced in the city gardener trend, and continually tries to squeeze a coterie of different plants in neatly compacted 1 square foot spaces.

The value each provides the garden is seemingly unimportant with respect to the goals of the other. From an individual perspective the marginal utility of her collaborators is 0.

And yet the garden, through the efforts of these three, is 10x more productive on any relevant metric, suggesting the marginal utility exists.

That’s specialization at its best.

**Comment by erikpukinskis** [comment]
Feel free to add that to the blog as an alumni post lol
